// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(dashboard)/main/(main)/(home)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/(home)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/admin/manage-charities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/admin/manage-charities">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/admin/manage-charities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/admin/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/admin/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/admin/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/groups">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/leaves/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/leaves">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/leaves/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/network">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/records">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/attendance/settings/sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/attendance/settings/sites">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/attendance/settings/sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/charities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/charities">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/charities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/charity-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/charity-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/charity-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/charity-meetings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/charity-meetings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/charity-meetings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/charity-meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/charity-meetings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/charity-meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/communication">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/contracts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/custom-surveys/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/custom-surveys/[id]/print">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/custom-surveys/[id]/results">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/custom-surveys/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/custom-surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/custom-surveys">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/custom-surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/design-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/design-requests">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/design-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/employees">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/employees/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/employees/roles">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/employees/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/finance/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/finance/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/finance/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/governance/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/governance/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/governance/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/governance/[name]/standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/governance/[name]/standards">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/governance/[name]/standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/governance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/governance/standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/governance/standards">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/governance/standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/landing-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/landing-settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/landing-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/mail/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/mail/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/mail/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/mail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/mail">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/mail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/manage-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/manage-services">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/manage-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/news">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/requests">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/resource-development/[name]/donors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/resource-development/[name]/donors">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/resource-development/[name]/donors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/resource-development/[name]/grants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/resource-development/[name]/grants">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/resource-development/[name]/grants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/services-overview/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/services-overview/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/services-overview/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/services-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/services-overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/services-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/hexagonal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]/hexagonal">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/hexagonal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]/report">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/stages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]/stages">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/stages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/vision-mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/strategy/[name]/vision-mission">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/vision-mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/surveys">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/template-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/template-library">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/template-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/workflow-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/workflow-settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/workflow-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/hexagonal/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/main/hexagonal/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/hexagonal/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/book-meeting/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book-meeting/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/book-meeting/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/charity-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charity-login">> = Specific
  const handler = {} as typeof import("../../src/app/charity-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/custom-survey/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/custom-survey/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/custom-survey/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hexagonal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hexagonal">> = Specific
  const handler = {} as typeof import("../../src/app/hexagonal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-preview">> = Specific
  const handler = {} as typeof import("../../src/app/landing-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/design-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/design-requests">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/design-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/governance">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/governance/standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/governance/standards">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/governance/standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/hr/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/hr/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/hr/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/hr">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/hr/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/hr/reports">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/hr/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/hr/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/hr/settings">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/hr/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/mail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/mail">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/mail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/no-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/no-access">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/no-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/services">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/[name]/templates">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portals">> = Specific
  const handler = {} as typeof import("../../src/app/portals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/charity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy/charity">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/charity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy/employees">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results">> = Specific
  const handler = {} as typeof import("../../src/app/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/select-charity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-charity">> = Specific
  const handler = {} as typeof import("../../src/app/select-charity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/survey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/survey">> = Specific
  const handler = {} as typeof import("../../src/app/survey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/survey/vision-mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/survey/vision-mission">> = Specific
  const handler = {} as typeof import("../../src/app/survey/vision-mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/attendance-close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/attendance-close">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/attendance-close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/design-auto-approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/design-auto-approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/design-auto-approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/[id]/copy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys/[id]/copy">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/[id]/copy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/[id]/regenerate-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys/[id]/regenerate-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/[id]/regenerate-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/[id]/responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys/[id]/responses">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/[id]/responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/[id]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys/[id]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/[id]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-surveys">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meetings/extract-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/extract-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/meetings/extract-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meetings/format/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/format">> = Specific
  const handler = {} as typeof import("../../src/app/api/meetings/format/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/submit-hexagonal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit-hexagonal">> = Specific
  const handler = {} as typeof import("../../src/app/api/submit-hexagonal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/submit-vision-mission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit-vision-mission">> = Specific
  const handler = {} as typeof import("../../src/app/api/submit-vision-mission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/survey-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/survey-links">> = Specific
  const handler = {} as typeof import("../../src/app/api/survey-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/upload-proof/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/upload-proof">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/upload-proof/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/main">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/main/(main)/strategy/[name]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/main/strategy/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/main/(main)/strategy/[name]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/charity-login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/charity-login">> = Specific
  const handler = {} as typeof import("../../src/app/charity-login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/custom-survey/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/custom-survey">> = Specific
  const handler = {} as typeof import("../../src/app/custom-survey/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hexagonal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hexagonal">> = Specific
  const handler = {} as typeof import("../../src/app/hexagonal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/hr/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal/[name]/hr">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/hr/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/[name]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/[name]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portals/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portals">> = Specific
  const handler = {} as typeof import("../../src/app/portals/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/survey/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/survey">> = Specific
  const handler = {} as typeof import("../../src/app/survey/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
